"""create teams

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-07 00:18:39.553094

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("hackathon_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("join_code", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathons.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hackathon_id", "name", name="uq_team_hackathon_name"),
        sa.UniqueConstraint("join_code"),
    )
    op.create_index(op.f("ix_teams_hackathon_id"), "teams", ["hackathon_id"], unique=False)
    op.create_index(op.f("ix_teams_public_id"), "teams", ["public_id"], unique=True)
    op.add_column("registrations", sa.Column("team_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_registrations_team_id"), "registrations", ["team_id"], unique=False)
    op.create_foreign_key(
        "fk_registrations_team_id_teams",
        "registrations",
        "teams",
        ["team_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_registrations_team_id_teams",
        "registrations",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_registrations_team_id"), table_name="registrations")
    op.drop_column("registrations", "team_id")
    op.drop_index(op.f("ix_teams_public_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_hackathon_id"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
