"""create attendance check-ins

Revision ID: 9d8bb15da04b
Revises: 0016
Create Date: 2026-09-01 15:01:13.102021

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9d8bb15da04b"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "check_in_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("hackathon_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["hackathon_id"], ["hackathons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        op.f("ix_check_in_sessions_token_hash"), "check_in_sessions", ["token_hash"], unique=True
    )
    op.create_index(
        "uq_check_in_sessions_one_active_per_hackathon",
        "check_in_sessions",
        ["hackathon_id"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_table(
        "check_ins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("registration_id", sa.Integer(), nullable=False),
        sa.Column("check_in_session_id", sa.Integer(), nullable=False),
        sa.Column(
            "checked_in_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["check_in_session_id"], ["check_in_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["registration_id"], ["registrations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("registration_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("check_ins")
    op.drop_index(
        "uq_check_in_sessions_one_active_per_hackathon",
        table_name="check_in_sessions",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_index(op.f("ix_check_in_sessions_token_hash"), table_name="check_in_sessions")
    op.drop_table("check_in_sessions")
    # ### end Alembic commands ###
