export const colors = {
  primary: '#1d4ed8',
  primaryHover: '#1e40af',
  primarySoft: '#e8edff',
  primarySurface: '#f1f5ff',
  primarySurfaceHover: '#f6f8ff',
  primaryBorder: '#bbc8ef',
  primaryBorderHover: '#98a9dd',
  danger: '#dc2626',
  dangerDark: '#a12b2b',
  dangerStrong: '#c72c41',
  dangerSoft: '#fde8e8',
  dangerSurface: '#fff0f0',
  success: '#22c55e',
  successDark: '#15803d',
  successText: '#18794e',
  successSoft: '#e6f7ef',
  warningText: '#8a5a00',
  warningSoft: '#fff3cd',
  text: '#111827',
  textMuted: '#6b7280',
  textSubtle: '#9ca3af',
  textSecondary: '#515a6b',
  background: '#ffffff',
  appBackground: '#f6f7fb',
  surfaceMuted: '#f3f4f6',
  surfacePrimaryHover: '#f2f5ff',
  border: '#e5e7eb',
  borderStrong: '#d1d5db',
  black: '#000000',
}

export const colorCssVariables = {
  '--color-primary': colors.primary,
  '--color-primary-hover': colors.primaryHover,
  '--color-primary-soft': colors.primarySoft,
  '--color-primary-surface': colors.primarySurface,
  '--color-primary-surface-hover': colors.primarySurfaceHover,
  '--color-primary-border': colors.primaryBorder,
  '--color-primary-border-hover': colors.primaryBorderHover,
  '--color-danger-dark': colors.dangerDark,
  '--color-danger-strong': colors.dangerStrong,
  '--color-danger-soft': colors.dangerSoft,
  '--color-danger-surface': colors.dangerSurface,
  '--color-success': colors.success,
  '--color-success-dark': colors.successDark,
  '--color-success-text': colors.successText,
  '--color-success-soft': colors.successSoft,
  '--color-warning-text': colors.warningText,
  '--color-warning-soft': colors.warningSoft,
  '--color-text': colors.text,
  '--color-text-muted': colors.textMuted,
  '--color-text-subtle': colors.textSubtle,
  '--color-text-secondary': colors.textSecondary,
  '--color-background': colors.background,
  '--color-app-background': colors.appBackground,
  '--color-surface-muted': colors.surfaceMuted,
  '--color-surface-primary-hover': colors.surfacePrimaryHover,
  '--color-border': colors.border,
  '--color-border-strong': colors.borderStrong,
  '--color-black': colors.black,
} as const

export const spacing = {
  xs: '4px',
  sm: '8px',
  md: '16px',
  lg: '24px',
  xl: '32px',
}

export const radius = {
  sm: '4px',
  md: '8px',
  full: '9999px',
}

export const typography = {
  fontFamily: 'system-ui, -apple-system, Segoe UI, sans-serif',
  sizeSm: '14px',
  sizeMd: '16px',
  sizeLg: '20px',
}
