JWT_ALGORITHM = "HS256"
DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES = 30
DEFAULT_REFRESH_TOKEN_EXPIRE_DAYS = 7
ACCESS_TOKEN_TYPE = "access"
REFRESH_TOKEN_TYPE = "refresh"
REVOKED_ACCESS_TOKEN_PREFIX = "auth:revoked_access_token:"
REFRESH_SESSION_PREFIX = "auth:refresh_session:"
REFRESH_TOKEN_COOKIE_NAME = "refresh_token"
